### ISSUE TITLE
python3 migration?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [ianling/letsencrypt-dns-bind9#1]
Hi,
is there any plan to migrate the script in python3? some linux distro like Fedora32 removed their python2 package, rather they have a legacy python2 package and to make python2 script to continue to work they have to change /usr/bin/pyhton call to /usr/bin/python27.

**Comment by ianling** [comment]
Just pushed a python3 version to master (the python2 version is backed up to the `python2` branch)

I no longer work at the company I originally wrote this script for, so I don't have an environment I can test it in. It should work exactly the same though, I only changed some syntax around to get it running in python3, the base functionality remains unchanged.

**Comment by ROBERT-MCDOWELL** [comment]
Ok will try it thank you very much!
btw, if you need a server access so tell me I will be glad to help
